services:
  - type: web
    name: ai-styler-backend
    env: python
    plan: free  # or whatever plan you use
    buildCommand: |
      apt-get update && apt-get install -y libgl1 libglib2.0-0
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: FLASK_ENV
        value: production
